compiler_inputs_sizes: Un-mainify UBSan ignorelist
We observe in a downstream CL (https://crrev.com/c/7090171) that
introducing a UBSan ignorelist causes `siso query deps` to treat it as
the "main file." I.E. the `deps` variable takes the form

```
[snip --- just a few keys preceding this]
'tools/ubsan/array_bounds_ignorelist.txt': {
  'apps/app_lifetime_monitor.cc',
  'apps/app_lifetime_monitor.h',
  'apps/app_lifetime_monitor_factory.cc',
  'apps/app_lifetime_monitor_factory.h',
  'apps/app_restore_service.cc',
[snip --- no keys after this]
```

and causes the script to fail with:

```
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/tools/clang/scripts/compiler_inputs_size.py", line 286, in <module>
    sys.exit(main())
             ^^^^^^
  File "/b/s/w/ir/cache/builder/src/tools/clang/scripts/compiler_inputs_size.py", line 270, in main
    raise Exception("Missing deps for '%s'" % f)
Exception: Missing deps for 'apps/app_lifetime_monitor.cc'
```

To treat this, exclude `.txt` files from being considered the "main
file."

Bug: 454399366
Change-Id: Id80f7066b41c26ef523e6cfcdcc887067d4c6392
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7099682
Auto-Submit: Kalvin Lee <kdlee@chromium.org>
Reviewed-by: Hans Wennborg <hans@chromium.org>
Commit-Queue: Hans Wennborg <hans@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1537984}
NOKEYCHECK=True
GitOrigin-RevId: 38b3b0b665d667591239897e7acc851262be0721