Mark some python variables global
Missed in https://crrev.com/c/6868589.

Causing issues like https://ci.chromium.org/ui/p/chrome/builders/ci/ToTWinOfficial/15503/overview

```
  File "C:\b\s\w\ir\cache\builder\src\tools\clang\scripts\build.py", line 1665, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\b\s\w\ir\cache\builder\src\tools\clang\scripts\build.py", line 848, in main
    WriteStampFile('', STAMP_FILE)
                       ^^^^^^^^^^

```

UnboundLocalError: cannot access local variable 'STAMP_FILE' where it is not associated with a value
Change-Id: I85b17ea577deae7407b07d9f020c7dfddd4ccd52
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6872233
Commit-Queue: Devon Loehr <dloehr@google.com>
Auto-Submit: Arthur Eubanks <aeubanks@google.com>
Reviewed-by: Devon Loehr <dloehr@google.com>
Cr-Commit-Position: refs/heads/main@{#1504591}
NOKEYCHECK=True
GitOrigin-RevId: 6ef2005dc6584c169602e1b30c8529c5753097df