spanify: Add mock `RawPtrTraits`
For now, just add `kAllowPtrArithmetic`. This is necessary when one has

```
// Given `raw_ptr<const int> miracleptr(foo)`:
std::copy(miracleptr.get(), &miracleptr[4], dest);
```

without which you would get

```
// synthetic line breaks added

../../base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr.h:736:9:
    error: static assertion failed due to requirement
    'raw_ptr_traits::IsPtrArithmeticAllowed(Traits)':
    cannot index raw_ptr unless AllowPtrArithmetic trait is present.
  736 |         raw_ptr_traits::IsPtrArithmeticAllowed(Traits),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../tools/memory/partition_allocator/klaus.cc:14:42:
    note: in instantiation of function template specialization
    'base::raw_ptr<const int>::operator[]<int, const int, void>' requested here
   14 |   std::copy(miracleptr.get(), &miracleptr[4], to.data());
      |                                          ^
```

Bug: 429881247
Change-Id: If3999af96ad7d4581c0e17e9a0a1e967a5724b6c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6801247
Commit-Queue: Kalvin Lee <kdlee@chromium.org>
Reviewed-by: Stephen Nusko <nuskos@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1503779}
NOKEYCHECK=True
GitOrigin-RevId: afc223d039604aed1b86a56f16d953190fe960ba